version: '3.8'
services:
  stats-server:
    build: stats/server
    image: dock_stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db-postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db-postgres:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=${DB_USER_NAME}:root
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}:root

  stats-db-postgres:
    image: postgres:14-alpine
    container_name: stats-db-postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=${DB_USER_NAME}:root
      - POSTGRES_PASSWORD=${DB_PASSWORD}:root

  ewm-service:
    build: main-service
    image: dock_ewm-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db-postgres
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db-postgres:5432/ewm-main
      - SPRING_DATASOURCE_USERNAME=${DB_USER_NAME}:root
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}:root
      - STATS_SERVER_URL=http://stats-server:9090

  main-db-postgres:
    image: postgres:14-alpine
    container_name: main-db-postgres
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=${DB_USER_NAME}:root
      - POSTGRES_PASSWORD=${DB_PASSWORD}:root