version: '3.8'
services:
  stats-server:
    build: stats/server
    image: dock_stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db-postgres
    # В финале ароли и имена cпрячу в переменные окружения
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db-postgres:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db-postgres:
    image: postgres:14-alpine
    container_name: stats-db-postgres
    ports:
      - "6541:5432"
    # В финале ароли и имена cпрячу в переменные окружения
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: main-service
    image: dock_ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"